# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "L!ar's Blog"
description: > # this means to ignore newlines until "email:"
   So close to the flame

email: qky1412@gmail.com
#blog logo
logo: "/assets/images/logo.png"
# blog cover
cover: "/assets/images/background_image.jpg"

name: 'qky'
author: 'qky'
author_image: "/assets/images/author.jpg"

comments:
provider: disqus
disqus:
short_name: qky1412

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/qky1412
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/kyle.qiu
    desc: Connect with me facebook
    share_url: //www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/qky1412
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://plus.google.com/103782074052192961897/posts
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:
